openapi: 3.0.3
info:
  title: Viagens API (em memória)
  version: "1.0"
servers:
  - url: http://localhost:8080
paths:
  /destinos:
    get:
      summary: Lista todos os destinos
      responses:
        '200':
          description: OK
    post:
      summary: Cadastrar destino
      requestBody:
        required: true
      responses:
        '201':
          description: Criado
  /destinos/{id}:
    get:
      summary: Visualizar destino por ID
      parameters:
        - name: id
          in: path
          required: true
      responses:
        '200':
          description: OK
    put:
      summary: Atualizar destino completo
      parameters:
        - name: id
          in: path
          required: true
      responses:
        '200':
          description: Atualizado
    patch:
      summary: Atualizar destino parcialmente
      parameters:
        - name: id
          in: path
          required: true
      responses:
        '200':
          description: Atualizado parcialmente
    delete:
      summary: Excluir destino
      parameters:
        - name: id
          in: path
          required: true
      responses:
        '204':
          description: Excluído
  /destinos/pesquisar/nome:
    get:
      summary: Pesquisar por nome
      parameters:
        - name: nome
          in: query
          required: true
  /destinos/pesquisar/localizacao:
    get:
      summary: Pesquisar por localização
      parameters:
        - name: localizacao
          in: query
          required: true
  /destinos/{id}/reservar:
    post:
      summary: Reservar pacote de viagem
      parameters:
        - name: id
          in: path
          required: true
